from enum import Enum

 
class TipoClienteEnum (Enum):
    HIPOTERAPIA = 1
    MONTA_TERAPEUTICA = 2 
    DEPORTE_ECUESTRE_ADAPTADO = 3
    ACTIVIDADES_RECREATIVAS = 4
    EQUITACION = 5

class SexoEnum(Enum):
    FEMENINO = 1
    MASCULINO = 2

class TipoEnum(Enum):
   FICHA_GENERAL_DEL_CABALLO = 1
   PLANIFICACION_DE_ENTRENAMIENTO = 2
   INFORME_DE_EVOLUCION = 3
   CARGA_DE_IMAGENES = 4
   REGISTRO_VETERINARIO = 5
